// Senate Constants
module.exports = {
    FIND_MEMBER: 'FIND_MEMBER',
    GET_DETAILS: 'GET_DETAILS',
    GET_RANDOM_DETAILS: 'GET_RANDOM_DETAILS',
    IDENTIFY_SECTION: 'IDENTIFY_SECTION',
    SET_CURRENT_MEMBER: 'SET_CURRENT_MEMBER',
    FLUSH_STORE: 'FLUSH_STORE'
};
