import SettingsData from '../data/settings.json';

export const Settings = SettingsData;

// Senate Constants
export default Object.freeze({
  FIND_MEMBER: 'FIND_MEMBER',
  GET_DETAILS: 'GET_DETAILS',
  IDENTIFY_SECTION: 'IDENTIFY_SECTION',
  SET_CURRENT_MEMBER: 'SET_CURRENT_MEMBER',
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  FLUSH_STORE: 'FLUSH_STORE',
  GET_SCHEDULE_A: 'GET_SCHEDULE_A',
  FIND_SPECIFIC_MEMBER: 'FIND_SPECIFIC_MEMBER',
  FEC_API_KEY: 'tFzROuk1OWWYiSxBDLRTIOL5c3TTK3LZ8Vj1AkQE',
  API_KEY: '4f501d505d514b85a01f39d4ceb9a353',
  GOOGLE_API_KEY: 'AIzaSyAIf11r3spH2a2wrjN3GKDbZJpzU_ekUfM',
  GOOGLE_CI_API_KEY: 'AIzaSyBvyYNyhM4ZV1jCaVluiNqUlIh3sfwLKd0',
  Settings: SettingsData,
});