// Senate Constants
module.exports = Object.freeze({
  FIND_MEMBER: 'FIND_MEMBER',
  GET_DETAILS: 'GET_DETAILS',
  GET_RANDOM_DETAILS: 'GET_RANDOM_DETAILS',
  IDENTIFY_SECTION: 'IDENTIFY_SECTION',
  SET_CURRENT_MEMBER: 'SET_CURRENT_MEMBER',
  FLUSH_STORE: 'FLUSH_STORE',
  FIND_SPECIFIC_MEMBER: 'FIND_SPECIFIC_MEMBER',
  API_KEY: '4f501d505d514b85a01f39d4ceb9a353',
});
